import React from 'react';
import { FileText, Download, CheckCircle, AlertTriangle } from 'lucide-react';

const SmartReport = ({ ticker, data, profile }) => {
    if (!data || !profile) return null;

    const stats = data.stats;
    const sentiment = profile.sentiment?.score || 3; // Default neutral

    // --- Logic Generation ---
    const generateSummary = () => {
        const volatility = stats.volatility;
        const sharpe = stats.sharpe_ratio;
        const trend = data.moving_averages.prices[Object.keys(data.moving_averages.prices).pop()] > data.moving_averages.ma_60[Object.keys(data.moving_averages.ma_60).pop()] ? "Bullish" : "Bearish";

        return `${ticker} is currently showing a ${trend} trend relative to its long-term moving average. ` +
            `With an annualized volatility of ${(volatility * 100).toFixed(1)}% and a Sharpe Ratio of ${sharpe?.toFixed(2)}, ` +
            `the asset presents a ${sharpe > 1 ? "favorable" : "challenging"} risk-adjusted return profile. ` +
            `Wall Street sentiment is currently leaning towards "${profile.sentiment?.key?.replace('_', ' ') || 'Neutral'}".`;
    };

    const generateStrengths = () => {
        const items = [];
        if (stats.sharpe_ratio > 1) items.push("Strong Risk-Adjusted Returns (Sharpe > 1)");
        if (stats.cagr > 0.10) items.push(`Double-digit Annual Growth (CAGR: ${(stats.cagr * 100).toFixed(1)}%)`);
        if (stats.max_drawdown > -0.20) items.push("Resilient Drawdown Profile (<20%)");
        if (profile.sentiment?.score < 2) items.push("Strong Analyst Buy Consensus");
        return items;
    };

    const generateRisks = () => {
        const items = [];
        if (stats.volatility > 0.25) items.push("High Volatility (>25%)");
        if (stats.sharpe_ratio < 0.5) items.push("Poor Risk-Reward Ratio");
        if (stats.max_drawdown < -0.40) items.push("Significant Historical Drawdown Risk");
        if (profile.sentiment?.score > 3.5) items.push("Negative Analyst Sentiment");
        if (items.length === 0) items.push("No critical red flags detected based on current metrics.");
        return items;
    };

    const summary = generateSummary();
    const strengths = generateStrengths();
    const risks = generateRisks();
    const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    return (
        <div className="max-w-4xl mx-auto animate-in fade-in duration-500">
            <div className="flex justify-between items-end mb-8 border-b border-navy/5 pb-6">
                <div>
                    <h2 className="text-3xl font-serif font-bold text-navy title-font">Smart Analyst Report</h2>
                    <div className="h-1 w-20 bg-gold mt-2"></div>
                </div>
                <button
                    onClick={() => window.print()}
                    className="flex items-center gap-2 text-sm font-bold text-navy hover:text-gold transition-colors"
                >
                    <Download className="w-4 h-4" />
                    EXPORT PDF
                </button>
            </div>

            <div className="bg-white p-10 rounded-none shadow-lg border-t-8 border-gold print:shadow-none">
                {/* Report Header */}
                <div className="flex justify-between mb-8">
                    <div>
                        <h1 className="text-4xl font-serif font-bold text-navy">{ticker}</h1>
                        <p className="text-slate-400 text-sm uppercase tracking-widest mt-1">Investment Memorandum</p>
                    </div>
                    <div className="text-right">
                        <p className="font-bold text-navy">{date}</p>
                        <p className="text-sm text-slate-400">Generated by Fuzile Solutions AI</p>
                    </div>
                </div>

                {/* Executive Summary */}
                <div className="mb-8">
                    <h3 className="text-sm font-bold text-gold uppercase tracking-widest mb-3 border-b border-beige-light pb-1">Executive Summary</h3>
                    <p className="font-serif text-lg leading-relaxed text-slate-700">
                        {summary}
                    </p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
                    {/* Bull Case */}
                    <div className="bg-green-50/50 p-6 rounded border border-green-100">
                        <h3 className="flex items-center gap-2 text-sm font-bold text-green-700 uppercase tracking-widest mb-4">
                            <CheckCircle className="w-5 h-5" />
                            Bull Case (Strengths)
                        </h3>
                        <ul className="space-y-3">
                            {strengths.map((item, i) => (
                                <li key={i} className="flex gap-2 text-slate-700 text-sm">
                                    <span className="text-green-500 font-bold">•</span> {item}
                                </li>
                            ))}
                        </ul>
                    </div>

                    {/* Bear Case */}
                    <div className="bg-red-50/50 p-6 rounded border border-red-100">
                        <h3 className="flex items-center gap-2 text-sm font-bold text-red-700 uppercase tracking-widest mb-4">
                            <AlertTriangle className="w-5 h-5" />
                            Bear Case (Risks)
                        </h3>
                        <ul className="space-y-3">
                            {risks.map((item, i) => (
                                <li key={i} className="flex gap-2 text-slate-700 text-sm">
                                    <span className="text-red-500 font-bold">•</span> {item}
                                </li>
                            ))}
                        </ul>
                    </div>
                </div>

                {/* Key Metrics Grid */}
                <div>
                    <h3 className="text-sm font-bold text-gold uppercase tracking-widest mb-4 border-b border-beige-light pb-1">Key Data Points</h3>
                    <div className="grid grid-cols-4 gap-4 text-center">
                        <div className="p-3 bg-slate-50 border border-slate-100">
                            <span className="block text-xs text-slate-400 uppercase">CAGR</span>
                            <span className="block text-xl font-bold text-navy">{(stats.cagr * 100).toFixed(1)}%</span>
                        </div>
                        <div className="p-3 bg-slate-50 border border-slate-100">
                            <span className="block text-xs text-slate-400 uppercase">Sharpe</span>
                            <span className="block text-xl font-bold text-navy">{stats.sharpe_ratio?.toFixed(2)}</span>
                        </div>
                        <div className="p-3 bg-slate-50 border border-slate-100">
                            <span className="block text-xs text-slate-400 uppercase">Beta</span>
                            <span className="block text-xl font-bold text-navy">{stats.trading?.beta?.toFixed(2) || '-'}</span>
                        </div>
                        <div className="p-3 bg-slate-50 border border-slate-100">
                            <span className="block text-xs text-slate-400 uppercase">Max DD</span>
                            <span className="block text-xl font-bold text-red-500">{(stats.max_drawdown * 100).toFixed(1)}%</span>
                        </div>
                    </div>
                </div>

                {/* Footer Disclaimers */}
                <div className="mt-12 text-[10px] text-slate-400 border-t border-slate-100 pt-4 text-justify">
                    <p>
                        <strong>Disclaimer:</strong> This report is generated algorithmically by Fuzile Solutions and does not constitute financial advice.
                        Past performance is not indicative of future results. Please conduct your own due diligence before making investment decisions.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default SmartReport;
